# Generated by Django 3.2.7 on 2021-12-17 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drftask', '0002_auto_20211217_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='name',
        ),
    ]
