# Generated by Django 3.2.7 on 2021-12-17 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drftask', '0004_alter_task_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task', to='drftask.assignment'),
        ),
    ]
