# Generated by Django 3.2.7 on 2021-12-20 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drftask', '0009_alter_favourite_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='favorite',
            new_name='myfavourite',
        ),
    ]
