# Generated by Django 3.2.7 on 2021-12-20 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drftask', '0010_rename_favorite_product_myfavourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='drftask.product'),
        ),
    ]
