# Generated by Django 3.2.7 on 2021-12-22 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drftask', '0019_alter_customer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customorder',
        ),
        migrations.AddField(
            model_name='order',
            name='customorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customorder', to='drftask.customer'),
        ),
    ]
