# Generated by Django 3.2.7 on 2021-12-22 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drftask', '0021_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rproducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=100)),
            ],
        ),
    ]
