# Generated by Django 3.2.7 on 2021-12-22 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drftask', '0023_alter_review_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='rproducts',
            name='fav',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rproducts',
            name='least',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rproducts',
            name='most_fav',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='drftask.rproducts'),
        ),
    ]
