# Generated by Django 3.2.7 on 2021-12-27 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drftask', '0026_alter_postmedia_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productthumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
